modLoader="javafml"
loaderVersion="[28,)"
license="GNU AGPL 3.0"
[[mods]]
modId="authwe"
version="${version}"
displayName="AuthWe"
logoFile= "assets/authwe/icon.png"
authors="cnlimiter"
description='''
Adds chat linking between QQ and Minecraft and QQ commands to request server data.
'''
