modLoader="javafml"
loaderVersion="[28,)"
license="GNU AGPL 3.0"
[[mods]]
modId="mcbot"
version="${version}"
displayName="McBot"
logoFile= "assets/mcbot/icon.png"
authors="cnlimiter"
description='''
Adds chat linking between QQ and Minecraft and QQ commands to request server data.
'''
